### ISSUE TITLE
CE Phoenix Cart v1.0.9.1 RCE Vulnerability

### ISSUE THREAD

**Issue by fairycn** [CE-PhoenixCart/PhoenixCart#43]
# introduction
Location admin/configuration.php?gID=10&cID=89&action=edit Page Log Destination information corresponding to the corresponding value of the configuration_value parameter corresponding to the value of the unfiltered cause of the existence of an override vulnerability, you can modify any suffix, customize the path to save the page, you can override the save to the non-website directory, admin/configuration  
# Vulnerability Analysis Details
https://github.com/fairycn/MySecurityResearch/blob/main/SafetyHazard/CE%20Phoenix%20Cart/CE%20Phoenix%20Cart%20v1.0.9.1%20RCE%20Vulnerability.md

**Comment by gburton** [comment]
This Vector is only available with **full access** to the Admin Area, right?
The shopowner must have given credentials of htpasswd and admin access to the bad actor to allow this.

**Comment by fairycn** [comment]
Yes this security risk can only be exploited when there are administrative privileges

**Comment by ecartz** [comment]
It also requires that there be a directory where PHP code can be run that is writable by the web server.  Because if the log path provided can't be written by the web server, you can't create the file there much less put content in it.  

I also don't follow how you are claiming your `eval` code works.  That particular configuration value does not use a use_function, so it is never invoked.  If it was, you wouldn't need the `eval` code.  It would already be run.  So the <?php part is entirely superfluous; I would expect it to block the functioning of an actual exploit.  

The file https://github.com/CE-PhoenixCart/PhoenixCart/releases/download/v1.0.9.1/update_1.0.9.0_1.0.9.1.zip does not include the code that you identified as the problem.  And that code wouldn't interact with the configuration entries you identify to cause the problem you describe.  

If you don't want to post an actual exploit online, feel free to create an account on the Phoenix Cart forum and send us a PM with the real details.  Or send us an email.  I'm not sure how much effort I'm going to put into trying to reproduce this without a better set of steps.

**Comment by fairycn** [comment]
I don't know why the Release file for the corresponding version doesn't have the full code, and the requirement is to download the full project file (which may just be an update patch and not contain the full code)
`https://github.com/CE-PhoenixCart/PhoenixCart/blob/master/admin/configuration.php`
I've updated the description of the reproduction article to make it more accessible and fixed some descriptive errors

**Comment by ecartz** [comment]
That isn't the "release file".  That's the update file for updating from the previous release to the current release.  The other two files would be more accurately named "release files".  I.e. the ones called "source code".  PHP is an interpreted language.  The source code is the release.  The code in the "Code Audit" has absolutely nothing to do with the identified issue, as it displays to the web page, not saves to the log file nor even to the configuration.  

I would also point out that a web server that allows writing code files to places where the files may be invoked and run as code is inherently misconfigured.  But regardless, I blocked this particular exploit.

**Comment by fairycn** [comment]
Well yes, I've just updated the detail display again to make it easier to understand the issue，

Thanks for understanding that this issue can be easily exploited by malicious people, leading to the writing of a file with a web backdoor via the logging function
